package bean;

// Generated 17-lug-2014 12.59.14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ContraddizioniId generated by hbm2java
 */
public class ContraddizioniId implements java.io.Serializable {

	private String idSintomo;
	private String NSint;
	private String idPaziente;
	private Date data;
	private String idCartella;
	private String idMedico;

	public ContraddizioniId() {
	}

	public ContraddizioniId(String idSintomo, String NSint, String idPaziente,
			Date data, String idCartella, String idMedico) {
		this.idSintomo = idSintomo;
		this.NSint = NSint;
		this.idPaziente = idPaziente;
		this.data = data;
		this.idCartella = idCartella;
		this.idMedico = idMedico;
	}

	public String getIdSintomo() {
		return this.idSintomo;
	}

	public void setIdSintomo(String idSintomo) {
		this.idSintomo = idSintomo;
	}

	public String getNSint() {
		return this.NSint;
	}

	public void setNSint(String NSint) {
		this.NSint = NSint;
	}

	public String getIdPaziente() {
		return this.idPaziente;
	}

	public void setIdPaziente(String idPaziente) {
		this.idPaziente = idPaziente;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public String getIdCartella() {
		return this.idCartella;
	}

	public void setIdCartella(String idCartella) {
		this.idCartella = idCartella;
	}

	public String getIdMedico() {
		return this.idMedico;
	}

	public void setIdMedico(String idMedico) {
		this.idMedico = idMedico;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContraddizioniId))
			return false;
		ContraddizioniId castOther = (ContraddizioniId) other;

		return ((this.getIdSintomo() == castOther.getIdSintomo()) || (this
				.getIdSintomo() != null && castOther.getIdSintomo() != null && this
				.getIdSintomo().equals(castOther.getIdSintomo())))
				&& ((this.getNSint() == castOther.getNSint()) || (this
						.getNSint() != null && castOther.getNSint() != null && this
						.getNSint().equals(castOther.getNSint())))
				&& ((this.getIdPaziente() == castOther.getIdPaziente()) || (this
						.getIdPaziente() != null
						&& castOther.getIdPaziente() != null && this
						.getIdPaziente().equals(castOther.getIdPaziente())))
				&& ((this.getData() == castOther.getData()) || (this.getData() != null
						&& castOther.getData() != null && this.getData()
						.equals(castOther.getData())))
				&& ((this.getIdCartella() == castOther.getIdCartella()) || (this
						.getIdCartella() != null
						&& castOther.getIdCartella() != null && this
						.getIdCartella().equals(castOther.getIdCartella())))
				&& ((this.getIdMedico() == castOther.getIdMedico()) || (this
						.getIdMedico() != null
						&& castOther.getIdMedico() != null && this
						.getIdMedico().equals(castOther.getIdMedico())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdSintomo() == null ? 0 : this.getIdSintomo().hashCode());
		result = 37 * result
				+ (getNSint() == null ? 0 : this.getNSint().hashCode());
		result = 37
				* result
				+ (getIdPaziente() == null ? 0 : this.getIdPaziente()
						.hashCode());
		result = 37 * result
				+ (getData() == null ? 0 : this.getData().hashCode());
		result = 37
				* result
				+ (getIdCartella() == null ? 0 : this.getIdCartella()
						.hashCode());
		result = 37 * result
				+ (getIdMedico() == null ? 0 : this.getIdMedico().hashCode());
		return result;
	}

}
