/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-07-18 10:39:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("\n");
      out.write("<title>Login</title>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<link href=\"css/default.css\" rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\tmedia=\"all\">\n");
      out.write("<link href=\"css/font.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\n");
      out.write("\n");
      out.write(" ");
  
 	int error = 0;
	 if (request.getAttribute("error") != null)
 		error = ((Integer)request.getAttribute("error"));
 
 
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div id=\"wrapper\">\n");
      out.write("\t\t<div id=\"header-wrapper\">\n");
      out.write("\t\t\t<div id=\"header\" class=\"container\">\n");
      out.write("\t\t\t\t<div id=\"logo\">\n");
      out.write("\t\t\t\t\t<h1>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">Ospedale San Gibbordano</a>\n");
      out.write("\t\t\t\t\t</h1>\n");
      out.write("\t\t\t\t\t<p>Divisione ospedaliera di Medicina</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div id=\"menu-wrapper\">\n");
      out.write("\t\t\t<div id=\"menu\" class=\"container\">\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li><a href=\"?\">Homepage</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"?ps=info\">Info</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"?ps=personale\">Personale</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"?ps=patologie\">Patologie</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"current_page_item\"><a href=\"?ps=login\">Login</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end #menu -->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<br>\n");
      out.write("\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<br>\n");
      out.write("\n");
      out.write("\t\t");
 if(error != 0) {
		
				switch(error){
				
				case 10: 
				
		
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t<div align=\"center\">\n");
      out.write("\t\t\t<div class=\"title\" style=\"color:Crimson;width:px;border-style:outset;background-color:Cornsilk;border-color:Red;margin:1ex;font-family:Courier 10 Pitch;padding:6;\">\n");
      out.write("\t\t\t\t<h1>Errore: <br>codice sanitario o password del paziente non corretti <br>\n");
      out.write("\t\t\t\t</h1>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t");
		
					break;
					
				case 20:
		
      out.write("\t\n");
      out.write("\t\t\t\t\t<div align=\"center\">\n");
      out.write("\t\t\t\t\t<div class=\"title\" style=\"color:Crimson;width:px;border-style:outset;background-color:Cornsilk;border-color:Red;margin:1ex;font-family:Courier 10 Pitch;padding:6;\">\n");
      out.write("\t\t\t\t<h1>Errore: <br>id o password del medico non corretti <br>\n");
      out.write("\t\t\t\t</h1>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t");
		break;
				default:
					break;
				}
		}
		
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div class=\"title\" align=\"center\">\n");
      out.write("\t\t\t<h2>LOGIN PAZIENTE</h2>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<form action=\"?ps=paziente\" method=\"post\" class=\"dark-matter\">\n");
      out.write("\t\t\tCodice Sanitario: <input type=\"text\" name=\"user\"><br>\n");
      out.write("\t\t\tPassword:\n");
      out.write("\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input\n");
      out.write("\t\t\t\ttype=\"password\" name=\"password\" class=\"textarea\"> <br>\n");
      out.write("\t\t\t<input type=\"submit\" class=\"button\">\n");
      out.write("\t\t</form>\n");
      out.write("\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<br>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div class=\"title\" align=\"center\">\n");
      out.write("\t\t\t<h2>LOGIN MEDICO</h2>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<form action=\"?ps=medico\" method=\"post\" class=\"dark-matter\">\n");
      out.write("\t\t\tID medico: <input type=\"text\" name=\"user\"><br> Password:\n");
      out.write("\t\t\t<input type=\"password\" name=\"password\" class=\"textarea\"> <br>\n");
      out.write("\t\t\t<input type=\"submit\" class=\"button\">\n");
      out.write("\t\t</form>\n");
      out.write("\n");
      out.write("\t\t<br> <br> <br>\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"banner2\"></div>\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
